import type { ChemicalDetails } from '~/api/types/listTypes';

export const chemicalDetailsMock: ChemicalDetails[] = [
  {
    id: '933458',
    dtxsid: 'DTXSID0020078',
    dtxcid: 'DTXCID3078',
    casrn: '12125-02-9',
    compoundId: 78,
    genericSubstanceId: 20078,
    preferredName: 'Ammonium chloride',
    activeAssays: null,
    molFormula: 'ClH4N',
    monoisotopicMass: 53.0032268,
    percentAssays: null,
    pubchemCount: 136,
    pubmedCount: 5177.0,
    sourcesCount: 66,
    qcLevel: 1,
    qcLevelDesc: 'Level 1: Expert curated, highest confidence in accuracy and consistency of unique chemical identifiers',
    isotope: 0,
    multicomponent: 1,
    totalAssays: null,
    toxcastSelect: null,
    pubchemCid: 25517,
    relatedSubstanceCount: 4,
    relatedStructureCount: 1,
    hasStructureImage: 1,
    iupacName: 'Ammonium chloride',
    smiles: '[NH4+].[Cl-]',
    inchiString: 'InChI=1S/ClH.H3N/h1H;1H3\n',
    averageMass: 53.49,
    qcNotes: '[1448438-95-6] and [152128-19-3] are Alternate CASRNs\' for this chemical; DTXSID401015131 and \r\nDTXSID501015134',
    qsarReadySmiles: null,
    msReadySmiles: null,
    irisLink: null,
    pprtvLink: null,
    isMarkush: false,
    cpdataCount: 1014,
    inchikey: 'NLXLAEXVIDQMFP-UHFFFAOYSA-N',
    wikipediaArticle: 'Ammonium chloride',
  }, {
    id: '1637742',
    dtxsid: 'DTXSID0020103',
    dtxcid: 'DTXCID60820620',
    casrn: '1327-53-3',
    compoundId: 820620,
    genericSubstanceId: 20103,
    preferredName: 'Arsenic oxide (As2O3)',
    activeAssays: 16,
    molFormula: 'As2O3',
    monoisotopicMass: 197.827934,
    percentAssays: 19.0,
    pubchemCount: 20,
    pubmedCount: 2384.0,
    sourcesCount: 67,
    qcLevel: 1,
    qcLevelDesc: 'Level 1: Expert curated, highest confidence in accuracy and consistency of unique chemical identifiers',
    isotope: 0,
    multicomponent: 1,
    totalAssays: 84,
    toxcastSelect: '16/84',
    pubchemCid: 14888,
    relatedSubstanceCount: null,
    relatedStructureCount: null,
    hasStructureImage: 1,
    iupacName: null,
    smiles: '[O--].[O--].[O--].[As+3].[As+3]',
    inchiString: 'InChI=1S/2As.3O/q2*+3;3*-2\n',
    averageMass: 197.84,
    qcNotes: 'Arsenic oxide (As2O5) [1303-28-2];  Arsenic oxide (As2O5): H2O (3:5) [12044-50-7]\r\nRecord was reviewed with Common Chemistry\r\n',
    qsarReadySmiles: null,
    msReadySmiles: null,
    irisLink: null,
    pprtvLink: null,
    isMarkush: false,
    cpdataCount: 37,
    inchikey: 'QTLQKAJBUDWPIB-UHFFFAOYSA-N',
    wikipediaArticle: 'Arsenic Trioxide',
  }, {
    id: '1037170',
    dtxsid: 'DTXSID0020153',
    dtxcid: 'DTXCID00153',
    casrn: '100-44-7',
    compoundId: 153,
    genericSubstanceId: 20153,
    preferredName: 'Benzyl chloride',
    activeAssays: 0,
    molFormula: 'C7H7Cl',
    monoisotopicMass: 126.0236279,
    percentAssays: 0.0,
    pubchemCount: 160,
    pubmedCount: 131.0,
    sourcesCount: 104,
    qcLevel: 1,
    qcLevelDesc: 'Level 1: Expert curated, highest confidence in accuracy and consistency of unique chemical identifiers',
    isotope: 0,
    multicomponent: 0,
    totalAssays: 234,
    toxcastSelect: '0/234',
    pubchemCid: 7503,
    relatedSubstanceCount: null,
    relatedStructureCount: null,
    hasStructureImage: 1,
    iupacName: '(Chloromethyl)benzene',
    smiles: 'ClCC1=CC=CC=C1',
    inchiString: 'InChI=1S/C7H7Cl/c8-6-7-4-2-1-3-5-7/h1-5H,6H2\n',
    averageMass: 126.58,
    qcNotes: null,
    qsarReadySmiles: 'ClCC1=CC=CC=C1',
    msReadySmiles: 'ClCC1=CC=CC=C1',
    irisLink: '393',
    pprtvLink: 'BenzylChloride',
    isMarkush: false,
    cpdataCount: 4,
    inchikey: 'KCXMKQUNVWSEMD-UHFFFAOYSA-N',
    wikipediaArticle: 'Benzyl chloride',
  },
];

export const altChemicalDetailsMock: ChemicalDetails[] = [
  {
    id: '933458',
    dtxcid: 'DTXCID3078',
    compoundId: 78,
    genericSubstanceId: 20078,
    activeAssays: null,
    molFormula: 'ClH4N',
    monoisotopicMass: 53.0032268,
    percentAssays: null,
    pubchemCount: 136,
    pubmedCount: 5177.0,
    sourcesCount: 66,
    qcLevel: 1,
    qcLevelDesc: 'Level 1: Expert curated, highest confidence in accuracy and consistency of unique chemical identifiers',
    isotope: 0,
    multicomponent: 1,
    totalAssays: null,
    toxcastSelect: null,
    pubchemCid: 25517,
    relatedSubstanceCount: 4,
    relatedStructureCount: 1,
    hasStructureImage: 1,
    iupacName: 'Ammonium chloride',
    smiles: '[NH4+].[Cl-]',
    inchiString: 'InChI=1S/ClH.H3N/h1H;1H3\n',
    averageMass: 53.49,
    qcNotes: '[1448438-95-6] and [152128-19-3] are Alternate CASRNs\' for this chemical; DTXSID401015131 and \r\nDTXSID501015134',
    qsarReadySmiles: null,
    msReadySmiles: null,
    irisLink: null,
    pprtvLink: null,
    isMarkush: false,
    cpdataCount: 1014,
    inchikey: 'NLXLAEXVIDQMFP-UHFFFAOYSA-N',
    wikipediaArticle: 'Ammonium chloride',
  },
];
